
set encoding=utf-8
scriptencoding utf-8
" set fileencodings=iso-2022-jp-3,iso-2022-jp,euc-jisx0213,euc-jp,utf-8,ucs-bom,euc-jp,eucjp-ms,cp932
set fileencodings=utf-8,ucs-bom,euc-jp,eucjp-ms,cp932

" python setting{{{
if has('win32') || has('win64')
  let g:python_host_prog = expand('~\python2\Scripts\python.exe')
  let g:python3_host_prog = expand('~\python3\Scripts\python.exe')
  if !has('nvim')
    set pythonthreedll=~\python3\Scripts\python36.dll
    set pythonthreehome=~\python3
  endif
else
  " let g:python_host_prog = expand('~/python2/bin/python')
  " let g:python3_host_prog = expand('~/python3/bin/python3.7')
  if !has('nvim')
    " vim自体が3.7に対応していない見たなので3.6を入れないと無理っぽい
    " set pythonthreedll=~/homebrew/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Python
  endif
endif
"}}}

let g:vimproc#download_windows_dll = 1

" dein {{{
let s:base_dir = '~/.cache/dein'
let s:dein_repos_dir = expand(s:base_dir) . '/repos/github.com/Shougo/dein.vim'
if !isdirectory(s:dein_repos_dir)
  if executable('git')
    call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repos_dir))
  else
    echomsg 'Not git'
  endif
endif

" deinの設定 
let &runtimepath .= ',' . s:dein_repos_dir
"let &runtimepath = s:dein_repos_dir . ',' . &runtimepath
unlet! s:dein_repos_dir

" テスト用
if 0
  call dein#begin(s:base_dir)
  call dein#end()
  finish
endif

if dein#load_state(s:base_dir)
  call dein#begin(s:base_dir)
  unlet! s:base_dir
  "call dein#load_toml(expand('<sfile>:h') . '/dein.toml')
  " Shougo
  call dein#add('Shougo/dein.vim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')
  call dein#add('Shougo/defx.nvim')
  call dein#add('Shougo/denite.nvim')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('Shougo/neocomplete.vim')     " 補完
  " call dein#add('Shougo/unite.vim')
  call dein#add('Shougo/neomru.vim')
  call dein#add('Shougo/neoyank.vim')
  call dein#add('Shougo/neoinclude.vim')      " 重いから有効にしてない
  call dein#add('Shougo/unite-outline')
  call dein#add('Shougo/vimproc.vim')
  call dein#add('Shougo/vimfiler')
  call dein#add('Shougo/vinarise.vim')
  call dein#add('Shougo/neco-vim')
  " other
  call dein#add('hachy/eva01.vim')            " カラースキーム
  call dein#add('vim-scripts/DirDiff.vim')
  call dein#add('tacroe/unite-mark')
  call dein#add('octol/vim-cpp-enhanced-highlight')
  call dein#add('tpope/vim-fugitive')         " 編集系、コマンドの直接実行
  call dein#add('cohama/agit.vim')            " コミットツリー表示、管理
  call dein#add('idanarye/vim-merginal')      " ブランチ管理
  call dein#add('airblade/vim-gitgutter')     " 編集中のファイルの差分情報表示
  " call dein#add('ryanoasis/vim-devicons')     " なんかアイコンのやつ
  call dein#add('kristijanhusak/defx-icons')  " なんかアイコンのやつがneovimでも表示できるようなやつ
  " call dein#add('kristijanhusak/defx-git')    " なんかアイコンのやつがneovimでも表示できるようなやつ
  call dein#add('fatih/vim-go')
  " call dein#add('easymotion/vim-easymotion')  " 移動するやつ
  call dein#add('thinca/vim-localrc')         " ローカル設定、プロジェクトの設定はだいたいこれでやったほうが楽な気がする
  call dein#add('scrooloose/nerdcommenter')   " コメントアウト   
  call dein#add('simeji/winresizer')
  " call dein#add('davidhalter/jedi-vim')
  call dein#add('dhruvasagar/vim-table-mode')
  call dein#add('haya14busa/vim-open-googletranslate')
  call dein#add('tyru/open-browser.vim')
  call dein#add('raghur/fruzzy')
  call dein#add('skanehira/translate.vim')
  call dein#add('previm/previm')
  " call dein#add('glidenote/memolist.vim')
  call dein#add('kmnk/denite-dirmark')
  call dein#add('tpope/vim-markdown')
  " call dein#add('callmekohei/defx-icons')
  " call dein#add('ryanoasis/vim-devicons')
  " call dein#add('deoplete-plugins/deoplete-tag')
  call dein#add('deoplete-plugins/deoplete-dictionary')
  call dein#add('Shougo/deoplete-clangx')
  " call dein#add('cocopon/vaffle.vim')
  " call dein#add('kristijanhusak/defx-git')
  " call dein#add('junegunn/vim-easy-align')
  call dein#add('mattn/sonictemplate-vim')
  call dein#add('mechatroner/rainbow_csv')
  call dein#add('elzr/vim-json')
  call dein#add('kana/vim-altr')
  call dein#add('itchyny/lightline.vim')
  call dein#add('jiangmiao/auto-pairs')
  call dein#add('majutsushi/tagbar')
  call dein#add('pepo-le/win-ime-con.nvim')
  call dein#add('tpope/vim-dispatch')
  call dein#add('janko-m/vim-test')
  call dein#add('aliev/vim-compiler-python')
  call dein#add('itchyny/calendar.vim')
  call dein#end()
  call dein#save_state()
endif
if dein#check_install()
  call dein#install()
endif
if len(dein#check_clean()) > 0
  call map(dein#check_clean(), "delete(v:val, 'rf')")
  call dein#recache_runtimepath()
endif
"}}}

filetype plugin indent on   "ファイルタイプ用のインデント設定を自動読み込みする

noremap s <Nop>
let g:mapleader = "s"

" plugin
if 0
  if dein#is_sourced('unite.vim') " {{{
    call unite#custom#profile('default', 'context', {
          \   'start_insert' : 0,
          \   'direction' : 'dynamicbottom'
          \ })
    call unite#custom#profile('action', 'context', {
          \   'start_insert' : 1
          \ })
    call unite#custom#profile('source/grep', 'context', {
          \   'buffer_name' : 'search-buffer',
          \   'empty' : 0
          \ })
    call unite#custom#profile('source/file_rec', 'context', {
          \   'buffer_name' : 'file-buffer',
          \ })
    call unite#custom#source('buffer,file,file_rec,bookmark', 
          \ 'sorter', 'sorter_selecta')
    nnoremap [unite] <Nop>
    " nmap , [unite]
    nnoremap <silent> [unite]f :<C-u>Unite file<CR>
    nnoremap <silent> [unite]g :<C-u>Unite grep:. <CR>
    nnoremap <silent> [unite]pg :<C-u>Unite grep:.:-w <CR>
    nnoremap <silent> [unite]tg :<C-u>Unite grep: <CR>
    nnoremap <silent> [unite]ptg :<C-u>Unite grep::-w <CR>
    nnoremap [unite]tw :<C-u>Unite grep:. <CR><C-R><C-W>
    nnoremap [unite]w :<C-u>Unite grep:. <CR><C-R><C-W>
    nnoremap [unite]pw :<C-u>Unite grep:.:-w <CR><C-R><C-W>
    nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
    nnoremap <silent> [unite]ta :<C-u>Unite tab<CR>
    nnoremap <silent> [unite]m :<C-u>Unite bookmark<CR>
    nnoremap <silent> [unite]a :<C-u>UniteBookmarkAdd<CR>
    nnoremap <silent> [unite]h :<C-u>Unite file_mru<CR>
    nnoremap <silent> [unite]y :<C-u>Unite history/yank<CR>
    nnoremap <silent> [unite]e :<C-u>Unite register<CR>
    nnoremap <silent> [unite]ch :<C-u>Unite change<CR>
    nnoremap <silent> [unite]j :<C-u>Unite jump<CR>
    nnoremap <silent> [unite]o :<C-u>Unite outline<CR>
    nnoremap <silent> [unite]l :<C-u>Unite launcher<CR>
    nnoremap <silent> [unite]k :<C-u>Unite mark<CR>
    nnoremap <silent> [unite]cu :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
    nnoremap <silent> [unite]rs :<C-u>UniteResume search-buffer<CR>
    nnoremap <silent> [unite]rf :<C-u>UniteResume file-buffer<CR>
    nnoremap <silent> [unite]i :<C-u>Unite giti<CR>
    nnoremap <silent> [unite]pi :<C-u>Unite mapping<CR>
    nnoremap <silent> [unite]s :<C-u>Unite output:message<CR>

    if executable('pt')
      " \でエスケープ -wで完全一致 正規表現とかスペースを入れるときは''か""で囲む
      let g:unite_source_grep_command = 'pt'
      let g:unite_source_grep_default_opts = '--nogroup --nocolor --smart-case -e'
      let g:unite_source_grep_recursive_opt = ''
      let g:unite_source_grep_encoding = 'utf-8'
    endif

    augroup unite_setting
      autocmd!
      autocmd FileType unite call s:unite_my_settings()
    augroup END
    function! s:unite_my_settings()
      nnoremap <silent><buffer><expr> <C-v> unite#do_action('vsplit')
      inoremap <silent><buffer><expr> <C-v> unite#do_action('vsplit')
      nnoremap <silent><buffer><expr> <C-s> unite#do_action('split')
      inoremap <silent><buffer><expr> <C-s> unite#do_action('split')
      nnoremap <silent><buffer><expr> <C-o> unite#do_action('open')
      inoremap <silent><buffer><expr> <C-o> unite#do_action('open')
      nnoremap <silent><buffer><expr> <C-e> unite#do_action('narrow')
      inoremap <silent><buffer><expr> <C-e> unite#do_action('narrow')
      nnoremap <silent><buffer><expr> <C-t> unite#do_action('tabopen')
      inoremap <silent><buffer><expr> <C-t> unite#do_action('tabopen')
    endfunction

    let s:unite_action_file_rec = {}
    function! s:unite_action_file_rec.func(candidate)
      call unite#start([['file_rec', a:candidate.action__path]])
    endfunction
    call unite#custom_action('directory', 'custom_file_rec', s:unite_action_file_rec)
    unlet! s:unite_action_file_rec

    let s:unite_action_directory_rec = {}
    function! s:unite_action_directory_rec.func(candidate)
      call unite#start([['directory_rec', a:candidate.action__path]])
    endfunction
    call unite#custom_action('directory', 'custom_directory_rec', s:unite_action_directory_rec)
    unlet! s:unite_action_directory_rec

    let s:unite_action_grep = {}
    function! s:unite_action_grep.func(candidate)
      call unite#start([['grep', a:candidate.action__path]])
    endfunction
    call unite#custom_action('directory', 'custom_grep', s:unite_action_grep)
    unlet! s:unite_action_grep

    call unite#custom#default_action('directory' , 'vimfiler')
  endif 
  " }}}
endif

if 0
  if dein#is_sourced('vimfiler') " {{{
    " カーソルが置かれているファイル、フォルダのパスを引数にしてコマンドを実行で
    " きるようしたい。
    let g:vimfiler_as_default_explorer = 0 " vim標準のファイラを置き換える
    let g:vimfiler_enable_auto_cd = 1      " 自動でカレントディレクトリ移動
    let g:vimfiler_safe_mode_by_default = 0
    "let g:vimfiler_ignore_pattern = ['^\.', '\.db$']
    let g:vimfiler_ignore_pattern = ['\.db$']
    let g:vimfiler_min_cache_files = 5000
    nnoremap <silent> <C-@> :<C-u>VimFilerBufferDir<CR>
  endif " }}}
endif

if dein#is_sourced('neocomplete.vim') && !has('nvim') "{{{
  " バッファ補完のみを有効に、他に重くない補完があればそれを使うようにしよう
	let g:acp_enableAtStartup = 0
  let g:neocomplete#enable_at_startup = 1 " 起動時に有効化
  let g:neocomplete#enable_smart_case = 1 " 大文字が入力されるまで大文字小文字の区別無視
  let g:neocomplete#auto_completion_start_length = 2      " 補完を表示する最小文字列
  let g:neocomplete#enable_underbar_completion = 1        " _区切りの補完を有効化 
  let g:neocomplete#max_list = 20         " 表示される候補の数
  let g:neocomplete#max_keyword_width = 200
  if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
  endif
  let g:neocomplete#keyword_patterns['default'] = '\h\w*'
  inoremap <expr> <C-g> neocomplete#undo_completion()
  " 共通の文字列を補完してくれる
  inoremap <expr> <C-l> neocomplete#complete_common_string()
  " <CR>: close popup and save indent.
  inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function()
    return (pumvisible() ? "\<C-y>" : "") . "\<CR>"
  endfunction
  " <TAB>: completion
  inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>" 
  " <C-h>, <BS>: close popup and delete backword char
  inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
  "inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
  inoremap <silent> <C-y> <C-y><C-[>
  if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
  endif
  let g:neocomplete#sources._ = ['buffer', 'member', 'file']
endif "}}}

if dein#is_sourced('winresizer') "{{{
  let g:winresizer_start_key="\<Leader>e"
endif "}}}

if dein#is_sourced('agit.vim') "{{{
  let g:agit_enable_auto_show_commit=1
endif "}}}

if 0
  if dein#is_sourced('vim-easymotion') "{{{
    let g:EasyMotion_startofline=0
    let g:EasyMotion_do_mapping=0
    let g:EasyMotion_smartcase=1
    map <Leader>s <Plug>(easymotion-s)
    map <Leader>f <Plug>(easymotion-bd-f2)
    map <Leader>j <Plug>(easymotion-bd-jk)
  endif "}}}
endif

if dein#is_sourced('nerdcommenter') "{{{
  let g:NERDSpaceDelims=1
  let g:NERDDefaultAlign='left'
endif "}}}

if dein#is_sourced('defx.nvim') "{{{
  nnoremap <silent> <Leader>d :<C-u>Defx `expand('%:p:h')` -search=`expand('%:p')`<CR>
  nnoremap <silent> <Leader>f :<C-u>Defx -split=vertical -winwidth=30 -direction=topleft<CR>
  augroup defx_settings
    autocmd!
    autocmd FileType defx call s:defx_my_settings()
  augroup END
	function! s:defx_my_settings() abort
	  " Define mappings
	  nnoremap <silent><buffer><expr> <CR>
	  \ defx#do_action('drop')
		" \ defx#is_directory() ?
		" \ defx#do_action('open') :
		" \ defx#do_action('multi', ['drop', 'quit'])
	  nnoremap <silent><buffer><expr> c
	  \ defx#do_action('copy')
	  nnoremap <silent><buffer><expr> m
	  \ defx#do_action('move')
	  nnoremap <silent><buffer><expr> p
	  \ defx#do_action('paste')
	  nnoremap <silent><buffer><expr> l
	  \ defx#do_action('open')
		" \ defx#is_directory() ?
		" \ defx#do_action('open') :
		" \ defx#do_action('multi', ['drop', 'quit'])
	  nnoremap <silent><buffer><expr> E
	  \ defx#do_action('open', 'vsplit')
	  nnoremap <silent><buffer><expr> P
	  \ defx#do_action('open', 'pedit')
	  nnoremap <silent><buffer><expr> o
	  \ defx#do_action('open_or_close_tree')
	  nnoremap <silent><buffer><expr> O
	  \ defx#do_action('open_tree_recursive')
	  nnoremap <silent><buffer><expr> K
	  \ defx#do_action('new_directory')
	  nnoremap <silent><buffer><expr> N
	  \ defx#do_action('new_file')
	  nnoremap <silent><buffer><expr> M
	  \ defx#do_action('new_multiple_files')
	  nnoremap <silent><buffer><expr> C
	  \ defx#do_action('toggle_columns',
	  \                'mark:indent:icon:filename:type:size:time')
    nnoremap <silent><buffer><expr> S
    \ defx#do_action('toggle_sort', 'time')
    nnoremap <buffer><expr> s
    \ defx#do_action('search', '.')
	  nnoremap <silent><buffer><expr> d
	  \ defx#do_action('remove')
	  nnoremap <silent><buffer><expr> r
	  \ defx#do_action('rename')
	  nnoremap <silent><buffer><expr> !
	  \ defx#do_action('execute_command')
	  nnoremap <silent><buffer><expr> x
	  \ defx#do_action('execute_system')
	  nnoremap <silent><buffer><expr> yy
	  \ defx#do_action('yank_path')
	  nnoremap <silent><buffer><expr> .
	  \ defx#do_action('toggle_ignored_files')
    nnoremap <silent><buffer><expr> ;
    \ defx#do_action('repeat')
	  nnoremap <silent><buffer><expr> h
	  \ defx#do_action('cd', ['..'])
	  nnoremap <silent><buffer><expr> ~
	  \ defx#do_action('cd')
	  nnoremap <silent><buffer><expr> q
	  \ defx#do_action('quit')
	  nnoremap <silent><buffer><expr> <Space>
	  \ defx#do_action('toggle_select') . 'j'
	  nnoremap <silent><buffer><expr> *
	  \ defx#do_action('toggle_select_all')
	  vnoremap <silent><buffer><expr> *
	  \ defx#do_action('toggle_select_visual')
	  nnoremap <silent><buffer><expr> j
	  \ line('.') == line('$') ? 'gg' : 'j'
	  nnoremap <silent><buffer><expr> k
	  \ line('.') == 1 ? 'G' : 'k'
	  nnoremap <silent><buffer><expr> <C-l>
	  \ defx#do_action('multi', ['redraw', 'clear_select_all'])
	  nnoremap <silent><buffer><expr> <C-g>
	  \ defx#do_action('print')
	  nnoremap <silent><buffer><expr> cd
	  \ defx#do_action('change_vim_cwd')
	  nnoremap <silent><buffer><expr> a
	  \ defx#do_action('add_session')
    nnoremap <silent> [denite]ds :<C-u>Denite defx/session<CR>
    nnoremap <silent> [denite]dh :<C-u>Denite defx/history<CR>
	endfunction
  let s:defx_sessions_path = expand('~/.vim/defx-sessions')
  if !isdirectory(s:defx_sessions_path)
    call mkdir(s:defx_sessions_path, "p")
  endif
  call defx#custom#option('_', {
        \ 'auto_cd': v:true,
        \ 'columns': 'mark:indent:icons:filename:type:size:time',
        \ 'show_ignored_files': v:true,
        \ 'session_file': s:defx_sessions_path . '/default',
        \ })
  unlet s:defx_sessions_path
  if has('nvim')
    " call defx#custom#option('_', {
    "       \ 'split': 'floating'
    "       \ })
  endif
  call defx#custom#column('time', {
        \ 'format': '%y/%m/%d %H:%M',
        \ })
  " call defx#custom#column('mark', {
  "       \ 'length': 2,
  "       \ })
  " call defx#custom#column('filename', {
  "       \ 'min_width': 50,
  "       \ 'max_width': 50,
  "       \ })
endif "}}}

if dein#is_sourced('vim-localrc') "{{{
  augroup vim_localrc_setting
    autocmd!
    " autocmd BufWinEnter * nested
    "       \   call localrc#load(g:localrc_filename)
    autocmd BufEnter * nested
          \   call s:project_my_settings()
  augroup END

  function! s:project_my_settings() abort
    let load_files = localrc#search(g:localrc_filename)
    if empty(load_files)
      let git_dir = finddir('.git', expand('%:p:h') . ';')
      if git_dir !=# ''
        let project_path = fnamemodify(git_dir . '/../', ':p')
        if isdirectory(project_path)
          execute('lcd ' . project_path)
          execute('setlocal path+=' . project_path . '**')
        endif
      endif
    else
      call localrc#load(g:localrc_filename)
    endif
  endfunction
endif "}}}

if dein#is_sourced('denite.nvim') "{{{
  augroup denite_settings
    autocmd!
    autocmd FileType denite call s:denite_my_settings()
  augroup END
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> a
          \ denite#do_map('choose_action')
    nnoremap <silent><buffer><expr> <TAB>
          \ denite#do_map('choose_action')
    nnoremap <silent><buffer><expr> l
          \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> <CR>
          \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> s
          \ denite#do_map('do_action', 'split')
    nnoremap <silent><buffer><expr> v
          \ denite#do_map('do_action', 'vsplit')
    nnoremap <silent><buffer><expr> t
          \ denite#do_map('do_action', 'tabopen')
    nnoremap <silent><buffer><expr> w
          \ denite#do_map('do_action', 'switch')
    nnoremap <silent><buffer><expr> d
          \ denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> p
          \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> h
          \ denite#do_map('move_up_path')
    nnoremap <silent><buffer><expr> q
          \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
          \ denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> <Space>
          \ denite#do_map('toggle_select').'j'
    nnoremap <silent><buffer><expr> <C-l>
          \ denite#do_map('redraw')
    nnoremap <silent><buffer><expr> m
          \ denite#do_map('quick_move')
	  nnoremap <silent><buffer><expr> j
          \ line('.') == line('$') ? 'gg' : 'j'
    nnoremap <silent><buffer><expr> k
          \ line('.') == 1 ? 'G' : 'k'
  endfunction

  augroup denite_filter_settings
    autocmd!
    autocmd FileType denite-filter call s:denite_filter_my_settings()
  augroup END
  function! s:denite_filter_my_settings() abort
	  imap <silent><buffer> <C-[> <Plug>(denite_filter_quit)
	  imap <silent><buffer> <CR> <Plug>(denite_filter_update)
  endfunction

  " For Pt(the platinum searcher)
  " NOTE: It also supports windows.
  call denite#custom#var('file/rec', 'command',
        \ ['pt', '--follow', '--nocolor', '--nogroup',
        \  (has('win32') ? '-g:' : '-g='), ''])
  " For python script scantree.py
  " Read bellow on this file to learn more about scantree.py
  " call denite#custom#var('file/rec', 'command', ['scantree.py'])

  " Change matchers.
  " call denite#custom#source(
  " \ 'file_mru', 'matchers', ['matcher/fuzzy', 'matcher/project_files'])
  call denite#custom#source(
        \ '_', 'matchers', ['matcher/fruzzy'])

  " Change sorters.
  call denite#custom#source(
        \ '_', 'sorters', ['sorter/rank'])

  call denite#custom#source(
        \ '_', 'max_candidates', 4000)

  call denite#custom#source('grep',
        \ 'converters', ['converter/abbr_word'])

  call denite#custom#kind('dirmark', 'default_action', 'candidate_file_rec')

  " Pt command on grep source
  call denite#custom#var('grep', 'command', ['pt'])
  call denite#custom#var('grep', 'default_opts',
        \ ['--nogroup', '--nocolor', '--smart-case', '--ignore=tags'])
        "\ ['-i', '--nogroup', '--nocolor', '--smart-case'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['-e'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  " Specify multiple paths in grep source
  "call denite#start([{'name': 'grep',
  "      \ 'args': [['a.vim', 'b.vim'], '', 'pattern']}])

  " Define alias
  call denite#custom#alias('source', 'file/rec/git', 'file/rec')
  call denite#custom#var('file/rec/git', 'command',
        \ ['git', 'ls-files', '-co', '--exclude-standard'])
  call denite#custom#alias('source', 'grep/git', 'grep')
  call denite#custom#var('grep/git', 'command',
        \ ['git', 'grep', '-i'])
  call denite#custom#var('grep/git', 'recursive_opts', [])
  call denite#custom#var('grep/git', 'pattern_opt', [])
  call denite#custom#var('grep/git', 'separator', ['--'])
  call denite#custom#var('grep/git', 'final_opts', [])
  call denite#custom#alias('source', 'file/rec/py', 'file/rec')
  call denite#custom#var('file/rec/py', 'command',['scantree.py'])

  let s:menus = {}
	let s:menus.my_commands = {
		\ 'description': 'commands'
		\ }
	let s:menus.my_commands.command_candidates = [
		\ ['Count character num', '%s/./&/gn'],
		\ ['Count word num', '%s/\i\+/&/gn'],
		\ ['Format Json', '%!python -m json.tool'],
		\ ]
  call denite#custom#var('menu', 'menus', s:menus)

  " Change default prompt
  call denite#custom#option('_', {
        \ 'auto_resize': v:true,
        \ 'empty': v:false,
        \ 'direction': 'dynamicbottom',
        \ 'max_candidate_width': 600,
        \ 'winwidth': &columns / 2 + 20,
        \ 'winheight': 30,
        \ 'smartcase': v:true,
        \ })
  if has('nvim')
    call denite#custom#option('_', {
          \ 'split': 'floating',
          \ })
  endif

  " Change ignore_globs
  " call denite#custom#filter('matcher/ignore_globs', 'ignore_globs',
  "       \ [ '.git/', '.ropeproject/', '__pycache__/',
  "       \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

  " Custom action
  " Note: lambda function is not supported in Vim8.
	function! s:candidate_file_rec(context)
	  let path = a:context['targets'][0]['action__path']
	  let narrow_dir = denite#util#path2directory(path)
	  let sources_queue = a:context['sources_queue'] + [[
	        \ {'name': 'file/rec', 'args': [narrow_dir]},
	        \ ]]
	  return {'sources_queue': sources_queue}
	endfunction
	call denite#custom#action('buffer,directory,file,openable,dirmark',
	        \ 'candidate_file_rec', function('s:candidate_file_rec'))

  " 候補にコマンドを実行
  " :Denite -resume -do='normal! A;'

  nnoremap [denite] <Nop>
  nmap , [denite]
  nnoremap <silent> [denite]n :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  nnoremap <silent> [denite]p :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>
  " nnoremap <silent> [denite]r :<C-u>Denite -resume<CR>
  nnoremap <silent> [denite]rg :<C-u>Denite -resume -buffer-name=search-buffer<CR>
  nnoremap <silent> [denite]rr :<C-u>Denite -resume -buffer-name=file-rec-buffer<CR>
  nnoremap <silent> [denite]ff :<C-u>Denite file<CR>
  nnoremap <silent> [denite]fr :<C-u>Denite file/rec<CR>
  nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
  nnoremap <silent> [denite]cf :<C-u>DeniteBufferDir file<CR>
  nnoremap <silent> [denite]cr :<C-u>DeniteBufferDir file/rec<CR>
  nnoremap <silent> [denite]g :<C-u>Denite -buffer-name=search-buffer grep<CR>
  nnoremap <silent> [denite]ig :<C-u>Denite -buffer-name=search-buffer -start-filter grep:::!<CR>
  nnoremap <silent> [denite]pg :<C-u>Denite -buffer-name=search-buffer grep::-w<CR>
  nnoremap <silent> [denite]w :<C-u>Denite -buffer-name=search-buffer `'grep:::' . expand('<cword>')`<CR>
  nnoremap <silent> [denite]pw :<C-u>Denite -buffer-name=search-buffer `'grep::-w:' . expand('<cword>')`<CR>
  nnoremap <silent> [denite]m :<C-u>Denite dirmark<CR>
  nnoremap <silent> [denite]a :<C-u>Denite dirmark/add<CR>
  nnoremap <silent> [denite]cg :<C-u>Denite change<CR>
  " nnoremap <silent> [denite]fg :<C-u>Denite
  "       \ `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`<CR>
  " nnoremap <silent> [denite]rg :<C-u>Denite
  "       \ `finddir('.git', ';') != '' ? 'grep/git' : 'grep'`<CR>
  nnoremap <silent> [denite]cs :<C-u>Denite colorscheme<CR>
  nnoremap <silent> [denite]co :<C-u>Denite command<CR>
  nnoremap <silent> [denite]ch :<C-u>Denite command_history<CR>
  nnoremap <silent> [denite]dr :<C-u>Denite directory_rec<CR>
  nnoremap <silent> [denite]fo :<C-u>Denite file/old<CR>
  nnoremap <silent> [denite]h :<C-u>Denite file_mru<CR>
  nnoremap <silent> [denite]j :<C-u>Denite jump<CR>
  nnoremap <silent> [denite]l :<C-u>Denite line<CR>
  nnoremap <silent> [denite]e :<C-u>Denite menu<CR>
  nnoremap <silent> [denite]o :<C-u>Denite outline<CR>
  nnoremap <silent> [denite]ss :<C-u>Denite output:message<CR>
  nnoremap <silent> [denite]re :<C-u>Denite register<CR>
  nnoremap <silent> [denite]so :<C-u>Denite source<CR>
  nnoremap <silent> [denite]t :<C-u>Denite tag<CR>
  nnoremap <silent> [denite]de :<C-u>Denite dein<CR>
  nnoremap <silent> [denite]dl :<C-u>Denite dein/log<CR>
  nnoremap <silent> [denite]k :<C-u>Denite mark<CR>
  nnoremap <silent> [denite]y :<C-u>Denite neoyank<CR>
endif "}}}

if dein#is_sourced('deoplete.nvim') "{{{
	" Use deoplete.
	let g:deoplete#enable_at_startup = 1
	" Use smartcase.
	call deoplete#custom#option('smart_case', v:true)
  " call deoplete#custom#option('sources', {'_': ['around', 'buffer', 'file', 'member', 'include']})
  call deoplete#custom#option('sources', {'_': ['around', 'buffer', 'file', 'member']})
  call deoplete#custom#var('around', {
        \   'mark_above': '[↑]',
        \   'mark_below': '[↓]',
        \   'mark_changes': '[*]',
        \})

	" <CR>: close popup and save indent.
	inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
	function! s:my_cr_function() abort
	  return deoplete#close_popup() . "\<CR>"
	endfunction
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ deoplete#manual_complete()
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction
  inoremap <expr><C-l> deoplete#refresh()
  inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
  inoremap <expr><BS>  deoplete#smart_close_popup()."\<C-h>"
  inoremap <expr><C-g> deoplete#undo_completion()
endif "}}}

if dein#is_sourced('vim-gitgutter') "{{{
  " nnoremap <silent> sn :GitGutterNextHunk<CR>
  " nnoremap <silent> sp :GitGutterPrevHunk<CR>
  if has('win32') || has('win64')
    let g:gitgutter_git_executable = expand('~\scoop\shims\git.exe')
  endif
  let g:gitgutter_diff_args = '-w'
endif "}}}

if dein#is_sourced('previm') "{{{
  if has('win32') || has('win64')
    let g:previm_open_cmd = '"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"'
  elseif has('mac')
    let g:previm_open_cmd = 'open -a Google\ Chrome'
  endif
endif "}}}

if dein#is_sourced('open-browser.vim') "{{{
	let g:netrw_nogx = 1 " disable netrw's gx mapping.
	nmap gx <Plug>(openbrowser-smart-search)
	vmap gx <Plug>(openbrowser-smart-search)
endif "}}}

if dein#is_sourced('vim-cpp-enhanced-highlight') "{{{
  let g:cpp_class_scope_highlight = 1
  let g:cpp_member_variable_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_concepts_highlight = 1
endif "}}}

if dein#is_sourced('vim-altr') "{{{
  call altr#define_defaults()
  nmap <Leader>n <Plug>(altr-forward)
  nmap <Leader>p <Plug>(altr-back)
endif "}}}

if dein#is_sourced('neoinclude.vim') "{{{
  if !exists('g:neoinclude#exts')
    let g:neoinclude#exts = {}
  endif
  let g:neoinclude#exts.cpp = ['', 'h', 'hpp', 'hxx']
  let g:neoinclude#ctags_command = ""
endif "}}}

if dein#is_sourced('lightline.vim') "{{{
  let g:lightline = {
        \ 'colorscheme': 'one',
        \ 'active': {
        \   'left': [['mode', 'paste'],
        \            ['fugitive', 'readonly', 'filename', 'modified']],
	      \   'right': [['syntastic', 'lineinfo'],
        \             ['percent'], 
        \             ['fileformat', 'fileencoding', 'filetype']]
        \ },
        \ 'component': {
        \   'lineinfo': ' %3l:%-2v',
        \ },
        \ 'component_function': {
        \   'readonly': 'LightlineReadonly',
        \   'fugitive': 'LightlineFugitive',
	      \   'fileformat': 'LightlineFileformat',
	      \   'filetype': 'LightlineFiletype',
	      \   'fileencoding': 'LightlineFileencoding',
        \ },
        \ 'separator': { 'left': '', 'right': '' },
        \ 'subseparator': { 'left': '|', 'right': '|' },
        \ 'tab': {
        \   'active': [ 'tabnum', 'filename', 'fullpath', 'modified' ],
        \   'inactive': [ 'tabnum', 'filename', 'modified' ] 
        \ },
        \ 'tab_component_function': {
        \   'fullpath': 'LightlineFilename'
        \ }
        \ }
	function! LightlineReadonly()
		return &readonly ? '' : ''
	endfunction
	function! LightlineFugitive()
		if exists('*fugitive#head')
			let branch = fugitive#head()
			return branch !=# '' ? ''.branch : ''
		endif
		return ''
	endfunction
  function! LightlineFilename(tabcount)
    let path = expand('%:p:h')
    return path !=# '' ? '(' . path . ')' : ''
  endfunction
	function! LightlineFileformat()
    let ff_table = {'dos' : 'CRLF', 'unix' : 'LF', 'mac' : 'CR' }
	  return winwidth(0) > 70 ? ff_table[&fileformat] : ''
	endfunction
	function! LightlineFiletype()
	  return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
	endfunction
	function! LightlineFileencoding()
	  return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
	endfunction
endif "}}}

if dein#is_sourced('defx-icons') "{{{
  let g:defx_icons_enable_syntax_highlight = 1
  let g:defx_icons_column_length = 2
  let g:defx_icons_directory_icon = ''
  let g:defx_icons_mark_icon = '*'
  let g:defx_icons_parent_icon = ''
  let g:defx_icons_default_icon = ''
  let g:defx_icons_directory_symlink_icon = ''
endif "}}}

if dein#is_sourced('tagbar') "{{{
  let g:tagbar_left = 1
  let g:tagbar_width = 90
  let g:tagbar_show_linenumbers = -1
  let g:tagbar_foldlevel = 1
endif "}}}

if dein#is_sourced('vim-test') "{{{
  let g:test#strategy = 'dispatch'
  " let g:test#project_root = 'C:\Users\taiki\ff-github\scripts\python\util'
endif "}}}
" 設定{{{
" packadd
if !has('nvim')
  packadd! matchit
endif
" 設定
" 表示
set termguicolors
set number        "行番号表示
"set relativenumber " 相対行番号表示
set title         "編集中のファイル名を表示
set showcmd       "入力中のコマンド表示
set ruler         "座標を表示
set showmatch     "対応する括弧を表示
set laststatus=2  "ステータスラインを表示
set nowrap        "端で折り返さない
set cursorline    "カーソルラインをハイライト
set cursorcolumn  "縦にもハイライト
set previewheight=36
set cindent
set cinoptions=g1,N-s,h1,l1,j1 "| setl foldmethod=indent
set scrolloff=8  "カーソルの上または下に表示される最低行数
set diffopt=internal,filler,indent-heuristic,algorithm:histogram
set cmdheight=2   "コマンドラインに使われる画面上の行数
set listchars=tab:>-,trail:-,nbsp:+
" set list
if has('nvim')
  set pumblend=15
  set winblend=15
endif
" set iminsert=0
"set scrolljump=5 "画面外に出た時にスクロールする行数
"set fileformat?  "e ++ff=dos "(CRLF) "e ++ff=mac "(LF)
"e ++enc=utf-8
" Anywhere SID.
function! s:SID_PREFIX()
  return matchstr(expand('<sfile>'), '<SNR>\d\+_\zeSID_PREFIX$')
endfunction
let g:ff_table = {'dos' : 'CRLF', 'unix' : 'LF', 'mac' : 'CR' }
function! s:MyStatusLine()
  let str = '%<%f %m%r%h%w%y'
  let str .= '[%{(&fenc!=""?&fenc:&enc)}]'
  let str .= '%{&bomb?"[BOM]":""}'
  let str .= '[%{ff_table[&ff]}]'
  let str .= '%{FugitiveStatusline()}'
  let str .= '%=%l/%L %4c %4P'
  return str
endfunction
" let &statusline = '%!' . s:SID_PREFIX() . 'MyStatusLine()'
function! s:MyTabLine()
  let str = ''
  for i in range(1, tabpagenr('$'))
    let bufnrs = tabpagebuflist(i)
    let bufnr = bufnrs[tabpagewinnr(i) - 1]  " first window, first appears
    let no = i  " display 0-origin tabpagenr.
    let mod = getbufvar(bufnr, '&modified') ? '!' : ' '
    let title = fnamemodify(bufname(bufnr), ':t')
    let title = '[' . title . ']'
    let str .= '%'.i.'T'
    let str .= '%#' . (i == tabpagenr() ? 'TabLineSel' : 'TabLine') . '#'
    let str .= no . ':' . title
    let str .= mod
    let str .= '%#TabLineFill# '
  endfor
  let str .= '%#TabLineFill#%T%=%#TabLine#'
  if tabpagenr('$') > 1
    let str .= '%999X[X]'
  endif
  return str
endfunction
" let &tabline = '%!'. s:SID_PREFIX() . 'MyTabLine()'
set showtabline=2 " 常にタブラインを表示
set matchpairs+=<:>
augroup setting_per_filetype
  autocmd!
  autocmd FileType c,cpp setl matchpairs+==:; | let b:match_words='if:else if:else,switch:case:default,#if:#else if:#else:#endif'
  autocmd FileType markdown,python setl shiftwidth=4 softtabstop=4 tabstop=4
  autocmd FileType vim setl foldmethod=marker
augroup END
augroup terminal_setting
  autocmd!
  autocmd TermOpen * setlocal statusline=%{b:term_title}
  autocmd TermOpen * setlocal list
augroup END
"set cindent       "C言語インデントに従って自動インデント
"set cinoptions=g1,N-s "スコープ宣言をブロックのインデントから１の位置に，namespaceはインデントしない
set expandtab     "タブをスペースに置き換え、タブ死すべし
set tabstop=2     "画面上でのタブ幅
set shiftwidth=2  "自動インデントでずれる幅
set shiftround    "インデントをshiftwidthの倍数に丸める
set softtabstop=2 "連続した空白でのタブやバックスペースで動く幅
set backspace=indent,eol,start
set whichwrap=b,s,h,l,<,>,[,] "カーソルを行頭，行末で止まらないように
set clipboard=unnamed "無名レジスタに
set wildmenu      "コマンドモードの補完
set wildmode=full
set nofixeol      "最後に改行のないファイルを編集したときに改行を付けない
set history=200   "コマンドラインモードの履歴を200に
"set textwidth=80 "グーグルコーディング規約に従って
"set colorcolumn=+1
"set foldcolumn=3
" ファイル
set hidden    "変更中でも他のファイルを開けるように
set autoread  "ファイル内容が変更されると自動読み込み
set undodir=~/.vim/undofile
set directory=~/.vim/swapfile   "スワップファイル
set backupdir=~/.vim/backupfile "バックアップファイル
" 検索
set incsearch "インクリメンタルサーチ
set hlsearch  "検索結果をハイライト
set ignorecase "大文字小文字を区別しない
set smartcase "検索時に大文字を含んでいたら大小を区別
set wrapscan  "検索をファイルの先頭へループ
"バイナリ編集(xxd)モード（vim -b での起動、もしくは *.bin ファイルを開くと発動します）
augroup binary_edit
  autocmd!
  autocmd BufReadPre  *.bin let &bin=1
  autocmd BufReadPost *.bin if &bin | %!xxd
  autocmd BufReadPost *.bin set ft=xxd | endif
  autocmd BufWritePre *.bin if &bin | %!xxd -r
  autocmd BufWritePre *.bin endif
  autocmd BufWritePost *.bin if &bin | %!xxd
  autocmd BufWritePost *.bin set nomod | endif
augroup END

command! -nargs=? Jq call s:jq(<f-args>)
function! s:jq(...)
  if a:0 == 0
    let arg = "."
  else
    let arg = a:1
  endif
  if executable('jq')
    execute '%! jq "' . arg . '"'
  else
    echomsg 'not found jq command'
  endif
endfunction

let s:session_path = expand('~/.vim/sessions')
if !isdirectory(s:session_path)
  call mkdir(s:session_path, "p")
endif
command! -nargs=1 SaveSession call s:saveSession(<f-args>)
function! s:saveSession(file_name)
  execute 'mksession!' s:session_path . '/' . a:file_name
endfunction
command! -nargs=1 LoadSession call s:loadSession(<f-args>)
function! s:loadSession(file_name)
  execute 'silent source' s:session_path . '/' . a:file_name
endfunction
command! -nargs=1 DeleteSession call s:deleteSession(<f-args>)
function! s:deleteSession(file_name)
  call delete(s:session_path . '/' . a:file_name)
endfunction
nnoremap <C-s> :<C-u>SaveSession default<CR>
nnoremap g<C-l> :<C-u>LoadSession default<CR>
nnoremap g<C-d> :<C-u>DeleteSession default<CR>
"}}}

" プラグインに関係ないキーマップ{{{
nnoremap / /\v
nnoremap ? ?\v
" 挙動をC、Dと同じにする
nnoremap Y y$
inoremap <silent> <ESC> <ESC>
inoremap <silent> <C-[> <ESC>
" inoremap <silent> <ESC> <ESC>:set iminsert=0<CR>
" inoremap <silent> <C-[> <ESC>:set iminsert=0<CR>
nnoremap <silent> <C-l> :<C-u>noh<CR><C-l>
nnoremap <silent> <C-]> g<C-]>
nnoremap <silent> <C-w>} <C-w>g}
noremap ; :
noremap : ;
" cnoremap ; :
" cnoremap : ;
nnoremap ' `
nnoremap <C-n> gt
nnoremap <C-p> gT
nnoremap gT :tabfirst<CR>
nnoremap gt :tablast<CR>
nnoremap <C-k> :tablast <bar> tabnew<CR>
" tnoremap <C-[> <C-W>N
cnoremap <A-b> <S-Left>
cnoremap <A-f> <S-Right>
tnoremap <Esc> <C-\><C-n>
tnoremap <expr> <C-R> '<C-\><C-N>"'.nr2char(getchar()).'pi'
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
inoremap <A-h> <C-\><C-n><C-w>h
inoremap <A-j> <C-\><C-n><C-w>j
inoremap <A-k> <C-\><C-n><C-w>k
inoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l
cnoremap <C-a> <Home>
cnoremap <C-b> <Left>
cnoremap <C-d> <Del>
cnoremap <C-e> <End>
cnoremap <C-f> <Right>
cnoremap <C-n> <Down>
cnoremap <C-p> <Up>
cnoremap <A-b> <S-Left>
cnoremap <A-f> <S-Right>
cnoremap <expr> / (getcmdtype() == '/') ? '\/' : '/'
vnoremap <C-a> <C-a>gv
vnoremap <C-x> <C-x>gv
" ドットコマンドが使えない
" nnoremap go :<C-u>call append(expand('.'), '')<CR>j
nnoremap go o<ESC>
nnoremap gO O<ESC>
inoremap jj <ESC>
inoremap っｊ <ESC>
"}}}

" MEMO{{{
" :r! date
" 再度コマンドを打つときはq:がいい気がする
" v_g_CTRL-A
" 10. ファイルを挿入する					*inserting-file*
" 文字数カウント
" command! Cc %s/./&/gn
" nnoremap <Leader>g :Gtags 
" nnoremap <Leader>r :Gtags -r 
" nnoremap <Leader>o :Gtags -f %<CR>
" nnoremap <Leader>c :GtagsCursor<CR>
" nnoremap <Leader>n :cn<CR>
" nnoremap <Leader>p :cp<CR>
"便利なマッピング					*useful-mappings*
"C のプログラムを編集する				*C-editing*
"*usr_29.txt*	For Vim バージョン 8.0.  Last change: 2016 Feb 27
"*41.11*	プラグインを書く				*write-plugin*
"単語や行などの数を数える				*count-items*
"	:%s/./&/gn		   文字
"	:%s/\i\+/&/gn		 単語
"	:%s/^//n		     行
"	:%s/the/&/gn		 "the" (どこかしら)
"	:%s/\<the\>/&/gn "the" (単語一致)
" inoremap <C-H> (
" inoremap <C-J> )
" inoremap <C-K> [
" inoremap <C-L> ]
" inoremap <C-D> *
" :%!python -m json.tool
" http://items.sjbach.com/319/configuring-vim-right	
" nnoremap 0 ^
" nnoremap ^ 0
" ヘルプ
" index
" eval
" functions
" function-list
"}}}

" gvim{{{
syntax on	            "シンタックスカラーリング
colorscheme eva01-LCL
"set background=dark
if has('nvim')
  if exists('g:GuiLoaded')
    GuiTabline v:false
    if has('mac')
      GuiFont! Cica:h14
    elseif has('win64') || has('win32')
      GuiFont! Cica:h9
    endif
  endif
else
  if has('mac')
    set guifont=Cica:h14
    set antialias
  elseif has('win64') || has('win32')
    set guifont=Cica:h11
    set renderoptions=type:directx,renmode:5
  endif
  set guioptions-=T    "ツールバー非表示
  set guioptions-=m    "メニュー非表示
  "set guioptions-=r    "右スクロールバー非表示
  set guioptions-=R
  set guioptions-=l    "左スクロールバー非表示
  set guioptions-=L
  set guioptions-=e    "gvimでもテキストベースのタブを使用する
  winpos 424 217  " 表示位置
  set lines=73    " 縦幅
  set columns=272 " 横
endif
set ambiwidth=double
"autocmd FocusGained * set transparency=100
"autocmd FocusLost * set transparency=30
"}}}

"eva01{{{
hi Comment cterm=NONE gui=NONE
hi Visual cterm=NONE gui=NONE
"hi Search ctermfg=97  ctermbg=119 cterm=NONE guifg=#875FAF guibg=#87FF5F gui=NONE
"hi Search cterm=NONE guifg=#D0D0D0 guibg=#875FAF gui=NONE
hi Search cterm=NONE guifg=#FFFFFF guibg=#875FAF gui=NONE
" hi Search cterm=NONE gui=NONE
" hi IncSearch cterm=NONE gui=NONE
hi! NormalFloat cterm=NONE guifg=#FFFFFF guibg=#875FAF gui=NONE
" vimdiffの色設定
" hi DiffAdd    gui=NONE guifg=#87FF5F guibg=#228B22
" hi DiffDelete gui=NONE guifg=#87FF5F guibg=#B22222
" hi DiffChange gui=NONE guifg=#87FF5F guibg=#3333CC
" hi DiffText   gui=NONE guifg=#87FF5F guibg=#0066FF
" floating window
" hi NormalFloat gui=NONE guifg=#87FF5F guibg=#585858
hi NormalFloat gui=NONE guifg=#D0D0D0 guibg=#585858
"}}}
